### ISSUE TITLE
TestFilght 0.0.2 Known Issues

### ISSUE THREAD

**Issue by jinwoong16** [APP-iOS5th/FinalProject-Kabinett#133]
## 프로필
- [ ] ~~첫 로그인시, 이메일 안 뜸~~
- [x] 탭바에 프로필 이미지 표시 #139 
- [x] 기존 유저 로그인시, 크래시 #143 

## 편지함
- [x] 편지 삭제랑 읽음 처리 박자가 늦음 #145 
- [x] 보관한 편지에 편지 내용이 하나도 없고, photoContent 만 왔을 때 첨부가 안 됨 (편지지만 뜸) #134 

## 편지 작성
- [x] UserSelection 모달이 마음대로 줄어듬 #137
- [x] 편지 작성 시 이미지 첨부 처음 튕기고, 두번째에 성공  #138 
- [x] '편지 선택하기' 텍스트 -> '이미지 선택하기' 텍스트로 바뀌면 좋을듯 #136 

## 편지 불러오기
- [x] #147
- [x] #148
- [x] #149
- [x] #150

## 처리한 것이면 이렇게 작성해주면 좋을 것 같아요.
- [x] 버그 수정 #{이슈번호}
