### ISSUE TITLE
TestFlight 0.3 Known Issues

### ISSUE THREAD

**Issue by jinwoong16** [APP-iOS5th/FinalProject-Kabinett#152]
## Misc
- [ ] + 눌렀을 때 흰 화면이 먼저 보였다.
- [ ] 애플로그인 후 이름 입력창이 아닌 메인 탭에 머물러 있었다.

## 앱 로고
- [x]  로고 왼쪽 흰 여백 보임 close #153 

## 프로필
- [x] 첫 로그인시, 이메일 안 뜸 #165 
- [ ] 회원탈퇴시 auth 정보가 그대로 남음
- [ ] 스와이프로 왔다갔다 하고 싶어요.

## 편지쓰기
- [x] 받는사람 검색 시 모달이 삐걱거린다. #161 
- [x] 편지지쓰기 키보드가 안내려간다. #160 
- [x] 편지 봉투 바깥쪽 보이는 부분을 윤원쟝꺼 맞춰서 !! #155

## 편지불러오기
- [x] #170
- [x] #171
- [x] #172
(뒤로가기로 처음화면 갔을 때, 보내고 처음화면으로 갔을 때 둘다 데이터 전부 초기화가 필요해요) 
- [ ] 이미지 피커로 사진 선택했을 때 디테일에서 사진이 왼쪽으로 기울어져 있습니다
- [x] #173
- [x] #174
- [x] #175
- [x] #176
- [x] #177
- [x] #178

## 편지함
- [x] 사진 없을 때도 옆으로 슬라이드가 된다 #156 
- [x] 스와이프로 왔다갔다 하고 싶어요. #156 
- [x] 편지지 본문에 '-에게, -가' 삭제하기 #156 
- [x] 필터화면 띄우고 화면을 여러번 터치하면 필터화면이 on off 반복됨 #163 
- [x] 필터 간 간격 띄우기 #163 

## Firebase 
- [x] 편지 삭제 시 photoContents도 삭제해야합니다. #159
