### ISSUE TITLE
Release 1.0 Known Issues & Refactoring Lists

### ISSUE THREAD

**Issue by jinwoong16** [APP-iOS5th/FinalProject-Kabinett#216]
## 편지봉투함페이지
- [x] 사용자가 바뀌었을 때 Refresh
- [x] 토스트바 시간 조정 #223

## 편지작성페이지
- [x] 편지봉투 뷰 통일해서 쓰기 + 네비게이션 수정하기 #253 
- [x] 편지 쓰기에 있는 미니 툴바 수정하기 #252 
- [ ] 편지 보관 버튼 클릭 후 닫는부분(편지불러오기)
- [ ] 편지 쓰기 도중 back 버튼 누르면 앱이 꺼짐 (?)
- [x] 편지 여러장 쓰기 #28 

## 탭
- [x] #227
- [x] #228

## 프로필페이지
- [x] 프로필 이미지 크롭할 때 특정 이미지에서 크롭이 제대로 되지 않음 #211 
- [x] 로그아웃, 회원탈퇴 후 로그인 유도 화면이 뜨기까지 2초의 시간이 걸림 #225 
- [x] 기존회원의 경우 재로그인 시 프로필 화면이 뜨기까지 1초 남짓의 시간이 걸림 #225 
- [ ] 설정 버튼 두번째 접속 시도 시, 안 들어가짐
- [ ] ProfileView DI Container 반영
- [ ] SignUpView DI Container 반영

## Data
- [x] firestoreLetterManager 볼륨 줄여보기
- [x] Welcome 편지 익명 확인 후 전송해주기 #219 
- [x] photoContent 삭제 로직 제거 #232 
- [x] 회원탈퇴하고 로그아웃하면 편지봉투함 업데이트 안됨 ,앱 종료 후 다시 시작할 때 리셋됨 #245 

## Design
- [x] 편지 봉투, 편지지, 우표 수정

## Application
- [x] #230
